name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Test
        run: mvn test
#      - name: Download Console Launcher # https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher
#        run: curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
#      - name: Build with javac
#        run: find . -name "*.java" -print | xargs javac -cp "junit-platform-console-standalone-1.8.2.jar" # Credits to https://stackoverflow.com/a/8332169/5108631
#      - name: Run tests
#        run: java -jar junit-platform-console-standalone-1.8.2.jar -cp "." --include-classname=.* --scan-classpath # Credits to https://stackoverflow.com/a/65976114/5108631
